### ISSUE TITLE
Unable to delete permanently from trash

### ISSUE THREAD

**Issue by taranvohra** [codesandbox/codesandbox-client#1186]
# 🐛 bug report
Unable to delete items from trash
## Description of the problem
I have a sandbox in trash for quite awhile, and when I try to delete it permanently it gives me an error. @CompuIves This issue was closed before but doesn't seem to have gone completely
###  Link to sandbox: [link]() (optional)
[GIF](http://g.recordit.co/x0OysAkpXC.gif)
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1539173261-ea48b8e
| Browser | Chrome 69.0.3497.100
| Operating System | Windows 7

**Comment by lbogdan** [comment]
Hey @taranvohra ,

I'm pretty confident this should be fixed. Can you please check, and if that's the case, close this? Thanks!

**Comment by taranvohra** [comment]
Hey @lbogdan, I just checked and seems like the error is still there. This is what is present in the console again,
```
Failed to load resource: the server responded with a status of 405 ()
vendors~app.76d08125.chunk.js:1 Uncaught (in promise) Error: Network error: Unexpected token < in JSON at position 0
    at new t (vendors~app.76d08125.chunk.js:1)
    at Object.error (vendors~app.76d08125.chunk.js:1)
    at m (vendors~app.76d08125.chunk.js:1)
    at v (vendors~app.76d08125.chunk.js:1)
    at e.value (vendors~app.76d08125.chunk.js:1)
    at m (vendors~app.76d08125.chunk.js:1)
    at v (vendors~app.76d08125.chunk.js:1)
    at e.value (vendors~app.76d08125.chunk.js:1)
    at Object.error (vendors~app.76d08125.chunk.js:1)
    at m (vendors~app.76d08125.chunk.js:1)
    at v (vendors~app.76d08125.chunk.js:1)
    at e.value (vendors~app.76d08125.chunk.js:1)
    at Object.error (vendors~app.76d08125.chunk.js:1)
    at m (vendors~app.76d08125.chunk.js:1)
    at v (vendors~app.76d08125.chunk.js:1)
    at e.value (vendors~app.76d08125.chunk.js:1)
    at vendors~app.76d08125.chunk.js:1
    at Array.forEach (<anonymous>)
    at vendors~app.76d08125.chunk.js:1
    at Array.forEach (<anonymous>)
    at Object.c [as error] (vendors~app.76d08125.chunk.js:1)
    at m (vendors~app.76d08125.chunk.js:1)
    at v (vendors~app.76d08125.chunk.js:1)
    at e.value (vendors~app.76d08125.chunk.js:1)
    at vendors~app.76d08125.chunk.js:1
```

**Comment by andreyberezhnoy** [comment]
@lbogdan i have same issue

```
Uncaught (in promise) Error: Network error: Unexpected token < in JSON at position 0
    at new t (bundle.esm.js:60)
    at Object.error (bundle.esm.js:1032)
    at m (Observable.js:130)
    at v (Observable.js:161)
    at e.value (Observable.js:220)
    at m (Observable.js:130)
    at v (Observable.js:161)
    at e.value (Observable.js:220)
    at Object.error (bundle.esm.js:48)
    at m (Observable.js:130)
    at v (Observable.js:161)
    at e.value (Observable.js:220)
    at Object.error (Observable.js:311)
    at m (Observable.js:130)
    at v (Observable.js:161)
    at e.value (Observable.js:220)
    at bundle.esm.js:69
    at Array.forEach (<anonymous>)
    at bundle.esm.js:69
    at Array.forEach (<anonymous>)
    at Object.d [as error] (bundle.esm.js:67)
    at m (Observable.js:130)
    at v (Observable.js:161)
    at e.value (Observable.js:220)
    at bundle.esm.js:84
```

**Comment by tlgreg** [comment]
Happens here too, seems like the `/api/graphql` endpoint returns with 405.
