### ISSUE TITLE
Template buttons are not accessible

### ISSUE THREAD

**Issue by NullVoxPopuli** [codesandbox/codesandbox-client#1754]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I cannot ctrl+click templates to open them in a new tab.
I cannot right click a template button to get the link to share with someone.

The template buttons are not links, and kinda goes against A11y efforts

![image](https://user-images.githubusercontent.com/199018/55884359-f159b480-5b75-11e9-91a3-c614d8e8a16c.png)

A fix should convert these to anchor tags with href populated

**Comment by CompuIves** [comment]
That's indeed very bad. In the case of the New Sandboox Page (codesandbox.io/s) we should pass a prop to the modal to show `a` elements instead. In the case of the dashboard it makes a bit less sense to show `a` because it does a POST request to create a sandbox, but we should at least make it a `button` there.

**Comment by tinahir** [comment]
Can I work on this bug?

**Comment by SaraVieira** [comment]
Issue fixed in #1761

**Comment by NullVoxPopuli** [comment]
This did not fix the issue

Navigation links should be anchor tags with hrefs :-\
