### ISSUE TITLE
Custom babel plugin in .babelrc with parcel is not working.

### ISSUE THREAD

**Issue by ismail-codar** [codesandbox/codesandbox-client#1935]
# 🐛 bug report

## Description of the problem
[This](https://codesandbox.io/s/github/ismail-codar/fidan-jsx-examples) can be work on local machine but codesanbox throws error.

Your can use "Export to ZIP" from codesanbox-client and can be run with the following commands on your local computer.
```shell
npm install
npm start
```

## How has this issue affected you? What are you trying to accomplish?
Trying [fidanjs](https://github.com/ismail-codar/fidan) demos on codesanbox

### Your Environment
Nodejs : v11.13.0

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | chrome latest
| Operating System | macos

**Comment by s-yadav** [comment]
I am facing the same issue. I am not able to add newly created babel-plugin on babelrc. 
It throws error `Could not find/install babel plugin`.
While the setup with parcel on local works well.

**Comment by s-yadav** [comment]
Is there any whitelisting of babel-plugins happening?

**Comment by Saw-mon-and-Natalie** [comment]
also facing the same issue trying to add `styled-jsx/babel` to `.babelrc` plugins section using the Vanilla JS template with `parcel`. I get this error:

```
Error
Could not find/install babel plugin 'styled-jsx/babel': 
Cannot find module '@babel/plugin-styled-jsx/babel' from '/src'
```

Does `codesandbox` only look at the `src` folder for babel plugins?

Repro: https://codesandbox.io/s/intelligent-roentgen-wi6e2

**Comment by siddharthkp** [comment]
Hey!

This is a bug 🐞 

Codesandbox optimises for plugins that follow the convention `babel-plugin-*`, this means that it missed `styled-jsx/babel`

There's some explanation in #2466 if you're curious to find out what happens under the hood.

**Comment by siddharthkp** [comment]
Hi @ismail-codar!

We pushed an update and you should be able to use `styled-jsx` and any other custom plugin now.

thanks @s-yadav and @Saw-mon-and-Natalie, your comments helped getting to the bug

If you have any other feedback, you know where to find us 😄

**Comment by ismail-codar** [comment]
But https://codesandbox.io/s/github/ismail-codar/fidan-jsx-examples is still not working. It looks my .babelrc is cannot be recognized.

**Comment by Saw-mon-and-Natalie** [comment]
@siddharthkp Thank you. I just tried using `styled-jsx` plug-in and it works.

**Comment by siddharthkp** [comment]
@Saw-mon-and-Natalie, great 👍

@ismail-coder, haven't had the chance to check this out. will keep this issue open until we know what's happening

**Comment by ismail-codar** [comment]
Woow https://codesandbox.io/s/github/ismail-codar/fidan-jsx-examples is working now. Thanks @siddharthkp and @CompuIves for  https://github.com/codesandbox/codesandbox-client/pull/2594

**Comment by siddharthkp** [comment]
That's great ✨!

If you have any feedback, you know where to find us 😄
