### ISSUE TITLE
codeSanbox imported from GitHub doesn't sync anymore

### ISSUE THREAD

**Issue by timoa** [codesandbox/codesandbox-client#1944]
# 🐛 bug report

## Description of the problem
When using CodeSandbox with an imported GitHub project and have some commits outside CodeSandbox on the same branch (master), the sandbox stop syncing.

I tried to open it in Chrome incognito mode and as a viewer to see if it was only my session but the sandbox is in the same state.

I also restarted many times the sandbox, the server, etc. but still stuck.

Only way is to recreate a new sandbox until the project stop syncing again. In this case, I can't share the link of the CodeSandbox because it changed all the time by creating new one :(

## How has this issue affected you? What are you trying to accomplish?
The sandbox become unusual and I need to create a new one each time to continue working on my project.

I also can't share the link since it changed each time when I create a new one.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/chrometabrotateserver-hpc5s

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1557935916-f212746b9 |
| Browser          | 74.0.3729.157 (Official Build) (64-bit) |
| Operating System | macOS 10.14.3 |

**Comment by lbogdan** [comment]
Hey @timoa ,

Did I get this right, is your issue that a sandbox forked from another github imported sandbox is not updated when you push new commits to the github repo? If so, that's expected behavior, as (maybe a bit poorly) documented in https://codesandbox.io/docs/git .

**Comment by timoa** [comment]
Hi @lbogdan!

Thanks for your reply!

The sandbox is not forked, I created a new sandbox from my GitHub repo and after it works well until I work from my Mac, push some commits and when I return to the Sandbox, it doesn't see the changes...

To reproduce:
1. Create a Sandbox from a GitHub repo
2. Commits changes from Sandbox
3. Git pull the changes from GitHub outside Sandbox (from another computer for example)
4. Create commit(s) and push them to GitHub
5. Open Sandbox and it will not see the new commit(s)
6. In this case, I restart a new Sandbox from the repo and kill the old one :(

**Comment by lbogdan** [comment]
So, let's rewind a bit:
- you have a github repo, let's call it `username/repo`
- you open it in CodeSandbox, using the `codesandbox.io/s/github/username/repo` URL, that creates a sandbox, let's call it `A`
- from that moment on, `A` will be linked to the repo, updating its contents as soon as someone loads it in the browser
- in order to work on it, you fork it, and you get a new sandbox, `B`
- you make changes to `B`, commit them to the repo from inside CodeSandbox, let's name the commit `c1`
- you clone (pull) the repo somewhere else, make changes to it, and commit them to the repo, let's name the commit `c2`

The current implementation makes it impossible to apply the `c2` commit to the `B` sandbox. It's not really a bug, more like a workflow limitation. The recommended workflow is, as you already mentioned, to remove `B`, fork another sandbox, make changes, commit them, remove the forked sandbox, and so on. You can think of the forked sandboxes `B` and `C` as feature branches, which you remove as soon as you merge them into `master`.

**Comment by muescha** [comment]
I think the Sandbox UI should help in this case

When i open sandbox B and it detects newer commits from github/name/repo (= A) then tehre should be a info (toast/row in navigation) about this and offer the next steps:

- do nothing and stay in current sanbox B at current status
- delete sandbox B and return to sandbox A to view changes
- delete sandbox B and create a new editable fork D to enterr directly into edit mode


PS:
Also the docs should be updated to show steps in case of newer commits in source repo

**Comment by muescha** [comment]
Not stale

**Comment by SaraVieira** [comment]
We have a new GitHub integration that does chaeck if you had updates on your repo and pulls them if you want

**Comment by SaraVieira** [comment]
Closed as we have fixed most issues with the Github Integration including pulling and pushing

**Comment by paul-pdftron** [comment]
I believe this issue still exists as i tried pushing to my github and do not see the changes in the sandbox.  I don't see an option to check for updates and pull them
