### ISSUE TITLE
Sandbox preview thumbnail never updates

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#2170]
# 🐛 bug report

## Description of the problem

The preview thumbnail for a sandbox never updates once it is created. This affects the dashboard view and the embed preview during loading.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 75.0.3770.142
| Operating System | Windows 10 / macOS

**Comment by lbogdan** [comment]
Hey @jsejcksn ,

Sorry for the delay. Indeed, there's no automatic refreshing of thumbnails ATM.

A workaround would be to manually access this URL: `https://codesandbox.io/api/v1/sandboxes/sandboxId/screenshot.png` .

**Comment by jsejcksn** [comment]
Hi @lbogdan: Thanks for responding. Is that URL documented somewhere?

**Comment by lbogdan** [comment]
It's not documented anywhere, as it's mostly an implementation detail. 🙂

Anyway, I'll leave this open until we find a proper solution.

**Comment by jsejcksn** [comment]
Is there a way to programmatically list all IDs for sandboxes in my dashboard other than by scraping? I would like to automate generating thumbnails periodically until there's a fix.

**Comment by thijsm** [comment]
Accessing the above url, `https://codesandbox.io/api/v1/sandboxes/sandboxId/screenshot.png`, doesn’t seem to generate a new screenshot. (I tried in a different browser, where the png wasn’t cached.)

A workaround seems to be to clone the sandbox (and delete the old one when you don’t want a Template reference to it).

**Comment by jsejcksn** [comment]
@thijsm Still works for me.

**Comment by andrasbacsai** [comment]
I've checked what's going on behind the scenes. I found a good solution to make it work. Will let you know about the outcome soon.

**Comment by andrasbacsai** [comment]
I've updated our screenshot microservice, but it's still just a workaround.

Now, if you modify a sandbox, you can programmatically generate a new screenshot with `https://codesandbox.io/api/v1/sandboxes/sandboxId/screenshot.png`. 

If you already had the screenshot cached in your browser, after 10 minutes it will be revalidated. So it means, in worst case, you will see the outdated screenshot for 10 minutes.

**Comment by jsejcksn** [comment]
https://github.com/codesandbox/codesandbox-client/issues/2170#issuecomment-518249450:
> Is there a way to programmatically list all IDs for sandboxes in my dashboard other than by scraping? I would like to automate generating thumbnails periodically until there's a fix.

@andrasbacsai Any ideas?

**Comment by andrasbacsai** [comment]
You can use our API endpoint (https://codesandbox.io/api/v1/sandboxes) for it.

I'm planning to modify this screenshot generating process a bit, so you do not have to do anything manually.

**Comment by andrasbacsai** [comment]
You can also play with our GraphQL & get data from it: https://codesandbox.io/api/graphiql

**Comment by jsejcksn** [comment]
@andrasbacsai Thanks for the information! I want to help keep the comments on-topic for this issue, but I'm interested in knowing more about the GraphQL and REST APIs. Where is the place for that (more info and/or discussion)?

**Comment by andrasbacsai** [comment]
We have updated our screenshot service. 

If you are on your dashboard and the screenshot of a sandbox in the current view (means you see it on your screen) is obsolete (means you have changed the code since the last screenshot), it will be regenerated automatically.  :tada: 

About the place for discussion: we only have Github for that, for example, the `Discussions` menu.

**Comment by SaraVieira** [comment]
Closing as it has been resolved 🎉

**Comment by Mannaio** [comment]
For me the issue is still present ad it is not clear to me at the end of this discussion what it has to be done from my side.
It is from days that some codesandboxes showing the default-sandbox-thumbnail and others showing the thumbnail of the codesandbox right.

See the screenshot of my sandboxes list

Any suggestion to fix that would be grateful

Thanks
<img width="1327" alt="codesandbox-thumbnail" src="https://user-images.githubusercontent.com/1617078/148384193-cb353b49-2e37-40e0-a322-327b97833edf.png">
s

**Comment by Izobov** [comment]
Hello! I have the same problem too... Saving new lines of code doesn't help to take a new screenshot.

And it would be great to be able to create a branded preview image
