### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by binkydog** [codesandbox/codesandbox-client#2216]
# 🐛 bug report
Not exactly a bug, but something's up with the cert for the browser window...
![image](https://user-images.githubusercontent.com/7891236/61894477-5e931a80-aec5-11e9-804b-42d06d6894d1.png)

## Description of the problem
Can't view running code...

## How has this issue affected you? What are you trying to accomplish?
Yes

### Link to sandbox: [link]() (optional)
Any

**Comment by coljung** [comment]
Oh yes, i thought It was only me.

On Chrome I simply get a blank screen, and Firefox shows the above message.

**Comment by CompuIves** [comment]
Hmm, my hunch is that csb.app is blocked by a firewall. I'm thinking that https://github.com/codesandbox/codesandbox-client/pull/2218 will fix this, I'm deploying that tonight!

**Comment by coljung** [comment]
@CompuIves Any updates on this by any chance ?

I just tested but none of my codesandbox windows display any demos still.

**Comment by CompuIves** [comment]
Can you try again right now? I deployed it a couple minutes ago.

**Comment by binkydog** [comment]
Working for me!  Thanks for quick response.

**Comment by coljung** [comment]
Still having issues.

Also, right now im working remotely and not connected via VPN, so im not on my company's network.

Issue is the same in Safari and Chrome. Firefox showed the error, but after a few reloads loaded the content.

Screenshot taken from Chrome:

![image](https://user-images.githubusercontent.com/917671/62056255-4552dc80-b1eb-11e9-8320-76283420b3c6.png)
