### ISSUE TITLE
Links to elements don't work

### ISSUE THREAD

**Issue by SaraVieira** [codesandbox/codesandbox-client#2231]
# 🐛 bug report

## Description of the problem

Adding a link to a certain element will not work on codesandbox

## How has this issue affected you? What are you trying to accomplish?
trying to navigate to an id

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |PROD-1564153504-2b37aae59
| Browser          |Chrome
| Operating System |Mac

**Comment by karlhorky** [comment]
Super interesting bug! This code seems like it could be related:

https://github.com/codesandbox/codesandbox-client/blob/bdfd72846324af470bca71693a2f04df1c593d30/packages/sandbox-hooks/url-listeners.js#L99-L138

**Comment by armujahid** [comment]
@SaraVieira Navigation to ids are working fine in your sandbox so I think this issue is fixed.

**Comment by karlhorky** [comment]
@armujahid Hm, still not working for me... (macOS Chrome `76.0.3809.132`)

**Comment by armujahid** [comment]
I tested it using latest chrome and Firefox on Linux. I will also add versions by updating my previous comment and will also test it on windows. This seems to be macOS specific issue.

**Comment by armujahid** [comment]
@karlhorky you are right. I tested it on Chrome 76.0.3809.132 (Official Build) (64-bit) on Linux and its not working in both "Project View" and "New Window". So this is not a macOS exclusive issue.

**Comment by armujahid** [comment]
Related: https://github.com/codesandbox/codesandbox-client/pull/198

**Comment by Oliver84** [comment]
I'm seeing this same issue. Any sandbox you build with a static HTML5 have this issues when trying to navigate to an internal ID on the page.

**Comment by moekhalil** [comment]
Please fix this. I sadly wasted hours that I will not be getting back due to this issue.

https://github.com/codesandbox/codesandbox-client/issues/4527

**Comment by armujahid** [comment]
This issue is still not resolved so I think this shouldn't be closed :)

**Comment by SaraVieira** [comment]
It is finally fixed 🎉

**Comment by karlhorky** [comment]
Awesome, thanks @SaraVieira !
