### ISSUE TITLE
Could not fetch dependencies, blocked by CORS policy

### ISSUE THREAD

**Issue by tay1orjones** [codesandbox/codesandbox-client#3748]
# 🐛 bug report

## Description of the problem

Dependencies fail to resolve. Error output from the console:
```
Access to fetch at 'https://aiwi8rnkp5.execute-api.eu-west-1.amazonaws.com/prod/packages/%40babel%2Fruntime%407.3.1+carbon-addons-iot-react%402.58.1+csbbust%401.0.0+react%4016.13.1+react-dom%4016.13.1+react-refresh%400.7.2' from origin 'https://95som.csb.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

POST https://aiwi8rnkp5.execute-api.eu-west-1.amazonaws.com/prod/packages/%40babel%2Fruntime%407.3.1+carbon-addons-iot-react%402.58.1+csbbust%401.0.0+react%4016.13.1+react-dom%4016.13.1+react-refresh%400.7.2 net::ERR_FAILED

Error in sandbox:
TypeError: Could not fetch dependencies, please try again in a couple seconds: Failed to fetch
``` 

## How has this issue affected you? What are you trying to accomplish?

I'm trying to use codesandbox as a way to show/reproduce bug reports for our [`carbon-addons-iot-react`](https://github.com/IBM/carbon-addons-iot-react) library.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1584982768-b051c4d19
| Browser          | chrome
| Operating System | macOS 10.14.5

**Comment by oskarabc** [comment]
I see a console error @tay1orjones, CORS issues should be fixed by now.

**Comment by tay1orjones** [comment]
@oskarabc This isn't fully resolved - there's no CORS error, but the dependencies are still failing to fetch.

The call to `https://aiwi8rnkp5.execute-api.eu-west-1.amazonaws.com/prod/packages/%40babel%2Fruntime%407.3.1+carbon-addons-iot-react%402.58.1+csbbust%401.0.0+react%4016.13.1+react-dom%4016.13.1+react-refresh%400.7.2` fails with the following response headers:
```
content-length: 41
content-type: application/json
date: Thu, 26 Mar 2020 21:40:27 GMT
status: 504
via: 1.1 44cd80eb280a376a14660d933d76c823.cloudfront.net (CloudFront)
x-amz-apigw-id: KBIfOFL7joEFg9Q=
x-amz-cf-id: VHyTW0Fjm_i-OPJwEOUovPZxH_fcHmRiepZrNLDsL82_zU9jY-BxWQ==
x-amz-cf-pop: DFW55-C1
x-amzn-errortype: InternalServerErrorException
x-amzn-requestid: 2b388f56-9d60-4ec3-9bf8-e8fd305b5131
x-cache: Error from cloudfront
```

subsequent retries also fail. I'm not sure how to debug this from my end?

**Comment by CompuIves** [comment]
Ah, yes, this one seems unrelated to our CORS issue from earlier. I'll reopen this one! I'll take a look at it today.

**Comment by CompuIves** [comment]
Update on this; didn't find yet what it could be. Continuing tomorrow...

**Comment by CompuIves** [comment]
Okay, I found the problem on why it doesn't happen properly. The lambda function that installs the dependencies goes out of disk space while installing the dependency, I find this very interesting because it does seem like we're able to install version `2.60.0` of the dependency (https://codesandbox.io/s/2020-03-24-iot-addons-dep-test-r4l2k).

I'm going to change how we fetch dependencies, so that even if the lambda function fails to install the dependency, we'd still be able to install it in the browser. I'll take a look at this today, can't promise whether I can finish it today though!

**Comment by tay1orjones** [comment]
Oh, that's odd. Particularly because the difference between `2.59.3` and `2.60.0` is a very small isolated change. We did update one of our dependencies though, and they also had updated their dependencies slightly. Perhaps something in that chain was causing a very large `node_modules` causing the disk space issue.

Either way, I really appreciate you taking the time to help us out with this!

**Comment by tay1orjones** [comment]
@CompuIves We've added example source code to our GitHub repo to standardize which template our bug reports should follow. The link sandbox link is
https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

It's failing with a CORS error. 
```
Access to fetch at 'https://aiwi8rnkp5.execute-api.eu-west-1.amazonaws.com/prod/packages/carbon-addons-iot-react%402.64.4' from origin 'https://nl0j5.codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Is there possibly a delay between when we release to npm and when the release is available in codesandbox?

**Comment by CompuIves** [comment]
Hmm interesting, it seems like the packager is out of space in this case as well.
![image](https://user-images.githubusercontent.com/587016/79369690-aa08bf80-7f51-11ea-9f7a-f0396a043b0a.png)

I think we should maybe move from using lambda functions to running the install in a docker container, which would give us more space than 500mb. In the meantime I can write a fallback that uses unpkg if the serverless resolver goes wrong!

**Comment by mrcnk** [comment]
I've got a similar issue adding the dependencies to a new sandbox.
`Access to fetch at 'https://aiwi8rnkp5.execute-api.eu-west-1.amazonaws.com/prod/packages/insites-ui%400.1.9' from origin 'https://dickf.csb.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`fetch-dependencies.ts:37 POST https://aiwi8rnkp5.execute-api.eu-west-1.amazonaws.com/prod/packages/insites-ui%400.1.9 net::ERR_FAILED`

**Comment by tay1orjones** [comment]
@CompuIves thanks again for looking into this 🙏 

Dependencies are still failing to install for me ([sandbox link](https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox)) - is there a config option or something else I need to configure?

**Comment by CompuIves** [comment]
Hey all here! I'm sorry for the late response, it was quite a bit of spelunking that had to be done to make this work. It turned out that our AWS Lambda service was running out of disk space in some cases, and because of this we had to move to a new service to install dependencies. I've now made a fallback service, that will be called when the main service doesn't have space, and the sandboxes with the errors should work properly now.

I'm really curious to hear whether this has solved your issues, please let me know!

**Comment by ben-rogerson** [comment]
> Hey all here! I'm sorry for the late response, it was quite a bit of spelunking that had to be done to make this work. It turned out that our AWS Lambda service was running out of disk space in some cases, and because of this we had to move to a new service to install dependencies. I've now made a fallback service, that will be called when the main service doesn't have space, and the sandboxes with the errors should work properly now.
> 
> I'm really curious to hear whether this has solved your issues, please let me know!

@CompuIves I'm seeing this issue today across many sandboxes - https://codesandbox.io/s/react-tailwind-emotion-starter-3d1dl

**Comment by SaraVieira** [comment]
@ben-rogerson That one seems to be fixed now aswell

**Comment by ben-rogerson** [comment]
@SaraVieira I'm seeing the error still at this sandbox:
https://codesandbox.io/s/react-tailwind-emotion-starter-3d1dl 
![image](https://user-images.githubusercontent.com/21288568/89950724-59884100-dc69-11ea-91d0-90f109c11f6e.png)

**Comment by CompuIves** [comment]
This seems to work now for me @ben-rogerson , does it work for you now as well?

**Comment by ben-rogerson** [comment]
Yes, working now for me 👍

**Comment by visualjeff** [comment]
It's back. 
<img width="555" alt="Screen Shot 2022-01-30 at 8 00 41 PM" src="https://user-images.githubusercontent.com/3446106/151737204-16eae83c-dc55-42f9-a2c9-080cdb837c01.png">
