### ISSUE TITLE
CodeSandbox see files that have been removed from the Docusaurus template

### ISSUE THREAD

**Issue by slorber** [codesandbox/codesandbox-client#5683]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [X] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

We recently updated the Docusaurus CodeSandbox template: https://github.com/facebook/docusaurus/tree/master/examples/classic

In particular this `docs` folder has changed a few times recently:
- https://github.com/facebook/docusaurus/tree/master/examples/classic/docs
- https://github.com/facebook/docusaurus/tree/v2.0.0-alpha.73/examples/classic/docs
- https://github.com/facebook/docusaurus/tree/v2.0.0-alpha.72/examples/classic/docs

But, when launching the template on CodeSandbox [new.docusaurus.io](https://new.docusaurus.io), we can see that CodeSandbox still see older files that have been removed from the template.

![image](https://user-images.githubusercontent.com/749374/115419668-cee5e180-a1fa-11eb-886e-7d1f810fd18d.png)

The files displayed here belong to some kind of merge between older/upstream template versions, and do not exactly match the files on master (https://github.com/facebook/docusaurus/tree/master/examples/classic/docs)

As Docusaurus now use the content of the `docs` folder to create its navigation UI, this problem becomes really apparent and our embedded tutorial is totally broken as it display stale docs:

![image](https://user-images.githubusercontent.com/749374/115420040-1ec4a880-a1fb-11eb-8bf7-df96ab34c25d.png)

For some reasons, those files only appear with the terminal command, not on the CodeSandbox UI:

![image](https://user-images.githubusercontent.com/749374/115420826-c17d2700-a1fb-11eb-8928-7cc51df0a521.png)

### To Reproduce

See above

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | docusaurus/master
| Browser          | Chrome
| Operating System | MacOS

---

In general, when I upgrade the Docusaurus CodeSandbox template on master, it is not always very clear how this change propagates, as it seems there is some kind of delay and caching layer on the CodeSandbox side. 
Is there some doc about this and the expectations I can have? 

Is there a way or a process to flush the cache and make sure our template is somehow reset to a clean state?

Thanks

**Comment by slorber** [comment]
@CodeSandboxTeam @SaraVieira wondering if you do something about it, our sandbox is broken.

Docusaurus just launched the first beta: https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta
And we have an important link to https://docusaurus.sse.codesandbox.io/docs/intro in our doc but it looks broken

Isn't there a way to somehow clear/reset this sandbox to fix this problem temporarily? 
Even if it's a one-shot and does not deeply fix the problem, I'm looking for a quick solution here.

**Comment by CompuIves** [comment]
Hey! Looking into this, we used to have a problem with GitHub where we didn't sync correctly a while ago, this might be a remnant from it. I just reimported the sandbox, and everything looks good now. Could you verify this as well?

Apologies for taking long to answer on this, it slipped through.

**Comment by CompuIves** [comment]
Ah no, I still see the extra documents here. Hmm, @lbogdan do you know how we sync the files between SSE and GitHub synced sandboxes?

Btw, congrats on the release!!

**Comment by CompuIves** [comment]
Just found that indeed our implementation has been adding the files between git syncs, we've reset the cache for now and will look further into it!

**Comment by SaraVieira** [comment]
Seems to be up now 🎉

**Comment by slorber** [comment]
thanks a lot! that is fixed now!

Will let you close the issue, as it looks like you still need to fix something so that it does not happen again

**Comment by slorber** [comment]
Hi there,

Not sure how it comes, but when I publish a new Docusaurus version and upgrade our examples, it is not reflected on our codesandbox

As far as I understand, https://codesandbox.io/s/docusaurus (using beta.3) is supposed to be in sync with https://github.com/facebook/docusaurus/tree/main/examples/classic (using beta.14).

It does not exactly look like a stale file issue this time, but can't be sure 🤷‍♂️

**Comment by sannek** [comment]
Oh, thanks for letting us know! It's now up to date again,  but for the future:

We only sync with github if you hit the sandbox from the `/s/github/facebook/docusaurus/tree/main/examples/classic` path and not from `/s/docusaurus` (I'm aware that this is counter-intuitive, and I'll bring it up with the team to see why we made that choice originally, and if we should not just always stay in sync regardless of the path)

(I'm going to close this issue - also because it's an old issue and should be resolved, but feel free to reopen, or add a new issue if needed!)

**Comment by slorber** [comment]
Oh I see thanks @sannek , sorry for the delay :)

Did you figure out why this sandbox does not sync/update when accessed this way?

Will accessing from one URL sync the sandbox to the other? (ie, I can resync things myself?)

**Comment by sannek** [comment]
It _should_ now update just fine when you hit the full url with "github" in it, but the issue was that `/s/docusaurus` was linked to an outdated version of your repo with a `master` branch instead of `main`, which couldn't update because `master `no longer exists.

I've had a story to deal with default banch renames on my backlog for a little bit, but had not yet found the time to fix it, sorry! I'll have a look in our db on Monday to see if any of the other docusaurus templates are also pointing to the wrong branch.

**Comment by slorber** [comment]
Thanks, I see 🤪 didn't think about this main branch update :D

**Comment by slorber** [comment]
@sannek we just released a new version beta.15

Initially, this one kept being beta.14: https://codesandbox.io/s/docusaurus

This one was successfully updated to beta.15: https://codesandbox.io/s/github/facebook/docusaurus/tree/main/examples/classic

And now this one was updated to beta.15: https://codesandbox.io/s/docusaurus

So I guess the sync issue is still there, and the workaround of hitting the github URL is still valid 

I'll hit the github URL then, just wanted to let you know ;)

**Comment by slorber** [comment]
Hey 👋 

We just released Docusaurus v3 and I think this problem is still there, and CodeSandbox see old files and eventually use stale cached node modules.

Is it possible to double-check those 2 sandboxes please?

- https://docusaurus.new/codesandbox
- https://docusaurus.new/codesandbox-ts

**Comment by CompuIves** [comment]
Hey! Looking into it, I think something went wrong with the update because the VM is still running Node v16 but Docusaurus requires Node v18. We're updating the default Node version soon, but in the meantime it can be fixed by creating a devcontainer configuration as follows:

`.devcontainer/devcontainer.json`:
```json
{
  "name": "Node.js",
  "image": "mcr.microsoft.com/devcontainers/javascript-node:18"
}
```

That will ensure that we use that docker image for the environment. Also, this will prompt users who open VSCode to use that Node version too.

I think we should be able to upgrade the default Node.js by next week, the challenge is backwards compatibility, so that's something we're solving first.

**Comment by slorber** [comment]
Thanks @CompuIves 

I'll try your solution soon, but wonder if this will be enough?

The problem is not only the wrong Node.js version, but also that the Sandbox shows duplicated files, like if an older sandbox and newer sandbox had been merged.

And also it seems to keep using Docusaurus 2.4.3 while package.json shows 3.0.0

![CleanShot 2023-11-10 at 19 07 14@2x](https://github.com/codesandbox/codesandbox-client/assets/749374/294fd562-149c-4086-b2ce-63a6c922b63e)

Looks like despite the Node.js error, it's using Node 20.9?

Not sure what is happening this this looks weird 😅

**Comment by CompuIves** [comment]
It does indeed look weird 😂. I'll check the duplicate files, I think maybe it could be introduced because the files were added to gitignore? I'll check tomorrow!

**Comment by slorber** [comment]
Hi @CompuIves, sorry to ping you on this but did you have time to find the cause of our broken sandbox? 
We have a link to it on our homepage and it doesn't look good for potential adopters if it doesn't work 😅

**Comment by CompuIves** [comment]
Ah sorry! I can take a look tonight!

**Comment by CompuIves** [comment]
It should be fixed now! We also default now to Node v20 for new sandboxes

**Comment by slorber** [comment]
Thanks, it seems to work better now 

Although I still get some strange behavior, like if CodeSandbox tried to run all docusaurus cli commands at once 🤪 Probably a different issue though.
https://codesandbox.io/p/sandbox/github/facebook/docusaurus/tree/main/examples/classic?file=%2FREADME.md`

<img width="612" alt="CleanShot 2023-11-23 at 22 49 37@2x" src="https://github.com/codesandbox/codesandbox-client/assets/749374/4e7c8267-4550-4d7a-b58e-0f58e9cb9a91">
