### ISSUE TITLE
Eslint throws when parsing TypeScript's Template Literal Types

### ISSUE THREAD

**Issue by gvergnaud** [codesandbox/codesandbox-client#6630]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Hey!

Looks like the version of eslint codesandbox uses doesn't support [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).

I noticed there is also an issue to disable eslint entirely for a project (#3401) which would probably solve my problem as well :)

### To Reproduce

Here is a sandbox reproducing the issue:

https://codesandbox.io/s/heuristic-kare-6siyr1?file=/src/index.ts

<img width="747" alt="image" src="https://user-images.githubusercontent.com/9265418/163569943-055ad044-5fb3-497d-b96a-a719e31d76c5.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |         ?     |
| Browser          |      Chrome 100.0.4896.88 (Official Build) (x86_64)   |
| Operating System |        MacOS      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by gvergnaud** [comment]
Hey, 

yes I've tried that but it doesn't work because eslint throws when parsing the content of the file (probably because the version used is outdated and doesn't know about the template literal type syntax), so before it's able to read comments.

**Comment by JamesACS** [comment]
@gvergnaud - This should now be fixed. Please could you confirm?

**Comment by gvergnaud** [comment]
👋 I can still see the issue on this sandbox: https://codesandbox.io/s/heuristic-kare-6siyr1?file=/src/index.ts

**Comment by DeMoorJasper** [comment]
We've reverted the change as it broke some other things. Working on a better fix
