### ISSUE TITLE
Unable to start the microVM

### ISSUE THREAD

**Issue by Eprince-hub** [codesandbox/codesandbox-client#8074]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
There is a Timed out error while trying to import a new project to codesandbox, I have tried doing it from the codesandbox dashboard by importing the repository I want and also have tried with githubox and all threw the same error `Unable to start the microVM`. Below is the detailed error message from Codesandbox

```error
Error: Error: Timed out after 5000ms
Version: 0c12b80
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: ksxmst
```

I also have the screenshot here👇

<img width="862" alt="Screenshot 2023-09-11 at 20 09 01" src="https://github.com/codesandbox/codesandbox-client/assets/74430629/9d5e98dd-4d61-4a6d-ae1e-8f73f1d98bea">

## How has this issue affected you? What are you trying to accomplish?

There is a similar issue here https://github.com/codesandbox/codesandbox-client/issues/7663 but the error messages differs

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Thanks for reporting this issue! This is an interesting one, I found the issue and it should. be resolved now. I will take a look in the meantime what caused this.

**Comment by CompuIves** [comment]
@Ajayghoshm could you verify again? I believe there was a bug in one of our proxies, which caused some connections to not resolve. The fix for this was deployed today, so if you had an issue before where the screen said "Connecting to MicroVM..." for a long time, that issue should be solved now.

**Comment by RBSUS** [comment]
This is happening here also: https://codesandbox.io/p/sandbox/github/tanstack/virtual/tree/beta/examples/react/dynamic?embed=1

**Comment by frog-o** [comment]
I having a similar here is mine.

<div class="c-PJLV c-PJLV-ichuRYQ-css" style="box-sizing: border-box; max-height: 140px; overflow: auto; color: rgb(153, 153, 153); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: border-box;">Error: (500) - URL: https://codesandbox.io/api/beta/sandboxes/branches/7vhf7z/instance - DATA: {"error":"UNKNOWN_ERROR - the connection was lost","code":"UNKNOWN_ERROR","message":"the connection was lost"} - ERROR: Error: (500) UNKNOWN_ERROR - the connection was lost</code></div><code style="box-sizing: border-box; color: rgb(153, 153, 153); font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Version: | 0.0.47
-- | --
Environment: | production
Event: | Initial connect to Pitcher
State: | ERROR
Branch: | 7vhf7z

</code>

I admit thou I am  doing a lot of sketchy thing such as `bind mount  /project/zshrc folder over /root `  and play around a lot in a a custom Dockerfile build in dev containerer.  I suspect I missing a debain package but this is hard to fix now.

What I want to do was have my .zshrc  cross docker containers.

**Comment by CompuIves** [comment]
Interesting, @frog-o could you share the link to the VM? I'll check if the VM had trouble to start.

**Comment by frog-o** [comment]
Sorry about that sure I think it here.
https://codesandbox.io/p/github/frog-o/codesandbox-client/frog-o/Testing?workspaceId=444aebca-547b-40d4-894a-b8ed880d48e8

I am failing miserably at trying to make a docker image. This is a good example of that.  What I wanted to do was put  My Home folder in the /project/(my-project)/Home/(My GitHub user).  Codesandbox doesn't talk much about this directory though or what needed to be included in the docker image for there terminal to run.  FNM needs to configure things with eval (FNM env) and there's no place to put it in right now before I flood you guys with issues on things I want to work on like this or even document them i need to figure out how to use them.

**Comment by frog-o** [comment]
@CompuIves  ,I done it [again](https://codesandbox.io/p/github/frog-o/codesandbox-client/draft/silly-robinson?workspaceId=444aebca-547b-40d4-894a-b8ed880d48e8l) won't start.  

I am pretty sure it has to do 
- with the mount not being right.   
-  the process gitting stuck on startup( I was load bash in setup task to trouble shoot) 

I think you need to reload the page.  Everything was work good yesterday until today when I went to  resume my work today.  I do a lot of weird thing thou.  I was putting 'bash and zsh' in the startup task so I could bug hunt.  I also was playing are in the developercontainers.json with the *CreateCommand( in other words postCreateCommand ,preCreateCommand.etc).  I am trying to build the [docker-debian-base](https://salsa.debian.org/jgoerzen/docker-debian-base) image and get it to run.

Yesterday it was giving error about  pitcher one of them being a missing directory so I made one of the the directory it was complaining about not existing  in the precreateComand(i Think).  

- One thing I know is a problem is that the terminal does not like not have root.   It is one Of the thing I had to change in my devcontainer.json file to get my terminal to open it would crash and reload  with me not being able to see the errors.
-  most Thing start automaticly and they should not at least with out some sort of delay so you can read errors and they should only try a compile of times.

This is really annoying bug.  I was getting close to have thing setup for usability like I wanted now I got to start again a square one.

**Comment by CompuIves** [comment]
I can check later today why that is happening. Really weird case though, even with bad configuration it should be possible to start at least.

**Comment by frog-o** [comment]
@CompuIves 
I done thing I should of and just to let you know I deleted my repository on codesandbox for this I want to start from scratch.
I have a lot of problem with it running out of disk space.  I look at the /root folder was 5 G .  This is odd I thought and look what was doing it.  It was the cache caches are not really need I thought in most case I could just delete that.  Well this is not one of those cases podman crash.   Yarn taking up a lot of space to.  I guess I can't work on codesandbox-client in code sandbox just because it to big for a free account.

**Comment by frog-o** [comment]
@Compulsves It look like you been busy; Things seem to be a lot more stable.  If nothing else I want to **Thank-you for your help**. I was ablly to get [docker-debian-base](https://salsa.debian.org/jgoerzen/docker-debian-base)  working and I see you (or some one) done a lot of work moving  folder around  in the /project/dir the way I like it. They also reconfigure git config  user.name to show the right info.  This has not gone un-notices. It was all thing preventing me from doing what I wanted before.

**Comment by silvanet** [comment]
I'm getting the same problem. I'm on Windows 11 (have also tried on W10). In codesandbox I forked a code sample app from a course I'm taking. It's a simple React app. I can figure out the dependencies and set this up on my local machine, but that's a long pain in the butt. I tried downloading my forked copy and got the convert to DevBox message. I did that. Then, the process began to create the micro VM. It ended with the same error messages reported by others and the same dialog.

To me this is more than just "interesting." I'd like to know how to get this to work.

**Comment by oxk4r01** [comment]
Same here. None of my devboxes can be opened :/

**Comment by oxk4r01** [comment]
In case it serves to someone, I was able to open devboxes by forking them.

**Comment by JamesACS** [comment]
@ysk3a - Sorry for any trouble. Any loading issues should now have been resolved. 

If you are still encountering the problem, please contact us via support@codesandbox.io with URLs for the effected environments and we'll take a closer look.

**Comment by Trashbin7** [comment]
This is still happening on March 22, 2024.

**Comment by seyedeliasfakoorian** [comment]
> This is still happening on March 22, 2024.

It is happening to me too

**Comment by CompuIves** [comment]
Can you verify that you can access "new.csb.app"? We've seen that some ISPs and corporate proxies block our csb.app domain, which is sometimes the source of this issue.

**Comment by CompuIves** [comment]
Opening issue for visibility.

**Comment by silvanet** [comment]
I'm not blocked. I see this:
Hello CodeSandboxStart editing to see some magic happen!

**Comment by seyedeliasfakoorian** [comment]
The last comment I wrote is still repeating

**Comment by seyedeliasfakoorian** [comment]
It happens with devboxes and github-imported repos

**Comment by CompuIves** [comment]
Could you share what the network tab in your devtools is showing when you filter in the network requests for `ctrl`? If you're getting it for all GH repos and devboxes I have a suspicion that there's a network wide block.

**Comment by waybig125** [comment]
Hi, @CompuIves I am getting a similar issue. The Micro VM isn't starting. It says:
Error: 
Version: 0.0.268
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: 9qhlzz
Here is the link to the project https://codesandbox.io/p/github/waybig125/sciencemaverick/main?workspaceId=ed3f647b-ba5f-4dd9-ae09-78c7ed634af3

The screenshot of the issue is attached. Please help me fix it. Thanks ):

![1711729293879](https://github.com/codesandbox/codesandbox-client/assets/92858750/56a56489-cb9a-47dc-824b-a3c2b7f525f1)

**Comment by CompuIves** [comment]
Thanks for the report @waybig125. I'm seeing that the authorize calls come in, but the websocket request doesn't come through. I'm checking why that is. To verify, could you share what you're seeing in your network tab for requests that contain `ctrl` in the URL?

**Comment by waybig125** [comment]
> Thanks for the report @waybig125. I'm seeing that the authorize calls come in, but the websocket request doesn't come through. I'm checking why that is. To verify, could you share what you're seeing in your network tab for requests that contain `ctrl` in the URL?

I am getting this error:
index.js:208 WebSocket connection to 'wss://9qhlzz.ctrl.codesandbox.io/?token=1vjx9722d2inzgep8l42' failed: 
(anonymous) @ index.js:208
Bs @ index.js:207
(anonymous) @ index.js:557

**Comment by CompuIves** [comment]
Does it show that the request immediately fails? Could you send a screenshot of the network panel? I think I'm getting closer to understanding what's happening

**Comment by waybig125** [comment]
Here is the screenshot
![error csb](https://github.com/codesandbox/codesandbox-client/assets/92858750/e92afb42-fe27-4cba-af9b-c33bfd5f0c9c)

**Comment by waybig125** [comment]
> Does it show that the request immediately fails? Could you send a screenshot of the network panel? I think I'm getting closer to understanding what's happening

But the most weird thing is that it is working fine on my mobile.

**Comment by CompuIves** [comment]
Hmm, in a terminal (if you're on Linux or Mac), could you run "curl -I https://9qhlzz.ctrl.codesandbox.io"? Curious what it returns

**Comment by CompuIves** [comment]
Or could you even open that url in the browser and show what your browser shows?

https://9qhlzz.ctrl.codesandbox.io

**Comment by waybig125** [comment]
> Hmm, in a terminal (if you're on Linux or Mac), could you run "curl -I https://9qhlzz.ctrl.codesandbox.io"? Curious what it returns

here is what i get:
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by waybig125** [comment]
And on visiting the url in the browser, it says:
Upgrade Required

**Comment by CompuIves** [comment]
Hmm, if it says Upgrade Required it means that you can connect to the endpoint. I'm going to check if we're rejecting any requests. It's weird that it works on your mobile, though. I'm wondering if maybe the DNS changes haven't propagated yet.

**Comment by waybig125** [comment]
> Hmm, if it says Upgrade Required it means that you can connect to the endpoint. I'm going to check if we're rejecting any requests. It's weird that it works on your mobile, though. I'm wondering if maybe the DNS changes haven't propagated yet.

I also tried another dns, but still didn't work.

**Comment by CompuIves** [comment]
This is what I get from running `curl`:

```
curl -I https://9qhlzz.ctrl.codesandbox.io
HTTP/2 426
date: Fri, 29 Mar 2024 19:18:54 GMT
content-type: text/plain
content-length: 16
cf-ray: 86c2355bb84ba004-AMS
cf-cache-status: DYNAMIC
strict-transport-security: max-age=31536000; includeSubDomains
set-cookie: _cfuvid=6VGgKf_lgKBexaCLFf.ySdw3XO2wu8ztlG8CAKEO5I8-1711739934206-0.0.1.1-604800000; path=/; domain=.codesandbox.io; HttpOnly; Secure; SameSite=None
server: cloudflare
alt-svc: h3=":443"; ma=86400
```

Makes me think there's maybe something going wrong there.

**Comment by waybig125** [comment]
> This is what I get from running `curl`:
> 
> ```
> curl -I https://9qhlzz.ctrl.codesandbox.io
> HTTP/2 426
> date: Fri, 29 Mar 2024 19:18:54 GMT
> content-type: text/plain
> content-length: 16
> cf-ray: 86c2355bb84ba004-AMS
> cf-cache-status: DYNAMIC
> strict-transport-security: max-age=31536000; includeSubDomains
> set-cookie: _cfuvid=6VGgKf_lgKBexaCLFf.ySdw3XO2wu8ztlG8CAKEO5I8-1711739934206-0.0.1.1-604800000; path=/; domain=.codesandbox.io; HttpOnly; Secure; SameSite=None
> server: cloudflare
> alt-svc: h3=":443"; ma=86400
> ```
> 
> Makes me think there's maybe something going wrong there.

Weird! It is rejecting my request with secure connection and with insecure connection, it gets me this error:
curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

**Comment by CompuIves** [comment]
What if you run the same curl command, but with `-vvv`? That will give more details on the handshake:

```
curl -vvv -I https://9qhlzz.ctrl.codesandbox.io
```

**Comment by waybig125** [comment]
> What if you run the same curl command, but with `-vvv`? That will give more details on the handshake:
> 
> ```
> curl -vvv -I https://9qhlzz.ctrl.codesandbox.io
> ```

This is what I got this time:
* Rebuilt URL to: https://9qhlzz.ctrl.codesandbox.io/
*   Trying 2606:4700:4400::ac40:9a6b...
* Connected to 9qhlzz.ctrl.codesandbox.io (2606:4700:4400::ac40:9a6b) port 443 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by CompuIves** [comment]
What environment (Windows/Linux/Mac) are you running the `curl` command in?

**Comment by waybig125** [comment]
> What environment (Windows/Linux/Mac) are you running the `curl` command in?

Mac OS X 10.11.6

**Comment by CompuIves** [comment]
Interesting. It seems like our root certificate is not accepted. Could you run `openssl s_client -connect 9qhlzz.ctrl.codesandbox.io:443 -servername 9qhlzz.ctrl.codesandbox.io
` and report back what's in the section `Certificate chain`?

**Comment by waybig125** [comment]
> openssl s_client -connect 9qhlzz.ctrl.codesandbox.io:443 -servername 9qhlzz.ctrl.codesandbox.io

It gave me this errror:
CONNECTED(00000003)
1480:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.2/src/ssl/s23_clnt.c:593:

**Comment by CompuIves** [comment]
Even more interesting, looks like the TLS version of your client is too low and gets rejected. I'm going to take a look at the Cloudflare settings.

**Comment by waybig125** [comment]
> Even more interesting, looks like the TLS version of your client is too low and gets rejected. I'm going to take a look at the Cloudflare settings.

Okay!

**Comment by CompuIves** [comment]
Could you try to run the same openssl/curl command again now?

**Comment by waybig125** [comment]
> openssl s_client -connect 9qhlzz.ctrl.codesandbox.io:443 -servername 9qhlzz.ctrl.codesandbox.io

GOt the exact same error!

**Comment by CompuIves** [comment]
Okay, and try once more :)

**Comment by waybig125** [comment]
this time I got this result:

* Rebuilt URL to: https://9qhlzz.ctrl.codesandbox.io/
*   Trying 2606:4700:4400::ac40:9a6b...
* Connected to 9qhlzz.ctrl.codesandbox.io (2606:4700:4400::ac40:9a6b) port 443 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Areeb-MacBook-Pro:~ admin$ openssl s_client -connect 9qhlzz.ctrl.codesandbox.io:443 -servername 9qhlzz.ctrl.codesandbox.io
CONNECTED(00000003)
1480:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.2/src/ssl/s23_clnt.c:593:
Areeb-MacBook-Pro:~ admin$ openssl s_client -connect 9qhlzz.ctrl.codesandbox.io:443 -servername 9qhlzz.ctrl.codesandbox.io
CONNECTED(00000003)
1515:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.2/src/ssl/s23_clnt.c:593:
Areeb-MacBook-Pro:~ admin$ openssl s_client -connect 9qhlzz.ctrl.codesandbox.io:443 -servername 9qhlzz.ctrl.codesandbox.io
CONNECTED(00000003)
depth=2 /C=US/O=Internet Security Research Group/CN=ISRG Root X1
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=ctrl.codesandbox.io
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFCzCCA/OgAwIBAgISA4ptkclru+Sh40mCXS1G3PN2MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yNDAzMjkxMzI3MTVaFw0yNDA2MjcxMzI3MTRaMB4xHDAaBgNVBAMT
E2N0cmwuY29kZXNhbmRib3guaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQChjZ2TKKSnVA0l/VcCJmWnffHpMl1pCyTIJbqL8mm3bFPJwh7RnygSc05f
BqTXWNbfSNo9R//IifGpKrT1iOLTMkdhFwrKNz0tjFP1/qfP9Sb2ouM7/Ogh91yh
/tQ//UCdW2d+vm5+tm/QUMm5uJu7YVOcggJPcwo0U1VDzz3nmgEYhYequJrv2Sd4
Rmt+5pe1CuIlhLIHVSZfBHiaoSxtAOqThW0o8ZcCC71Rvf822kFznYaVxvvhlVW8
FEYv8AL/5WB3vKZ6vGvDda+mas6yvmupqbhEsIk7N9gI13grnRRF8YrQNXHXf2SS
CkOBT28rLqN7aZNoMybQsherD+H/AgMBAAGjggItMIICKTAOBgNVHQ8BAf8EBAMC
BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
HQYDVR0OBBYEFBXvx20CkAr9AI1tyMoEThbR7WZNMB8GA1UdIwQYMBaAFBQusxe3
WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0
cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5j
ci5vcmcvMDUGA1UdEQQuMCyCFSouY3RybC5jb2Rlc2FuZGJveC5pb4ITY3RybC5j
b2Rlc2FuZGJveC5pbzATBgNVHSAEDDAKMAgGBmeBDAECATCCAQUGCisGAQQB1nkC
BAIEgfYEgfMA8QB3AEiw42vapkc0D+VqAvqdMOscUgHLVt0sgdm7v6s52IRzAAAB
joqbkq0AAAQDAEgwRgIhAOAfFH1CSfBTlYcR1bEiN5PILL44YFte8+fjEmLqjBt3
AiEA/AZ4yp+WCe1ymPCDYZii+Kmis1gNhOMLjYNaLBLb29oAdgDuzdBk1dsazsVc
t520zROiModGfLzs3sNRSFlGcR+1mwAAAY6Km5LEAAAEAwBHMEUCIQCK09EsDSrw
Q/jkqWFeOyVAmHeqA2tBC6SnhoPjophtswIgGXo/J7oPAWMNns24vAW/EK1tV//6
tIVicQCjCjtN4QEwDQYJKoZIhvcNAQELBQADggEBAI42OlO3aDF0ZRxJW2eJtt5e
h+F/yUIAjdYB+UwaKdG/vBj0ikTvpZPyJgeQldUDXoLJp4F5Bhjy+TyzpfneXQIT
DILWnlSJsovwFAxd7+Pacqo+MgOYgngtSSNsDOk6PO6ZBuQPmsO8hUoeIhKeXkwb
zoxRmo/DNPLzop/mj6i7IwSbUqXZRXEZAX0Vtk/0sTgSA8SzFSOlaby7iy+Ar4I8
xdL0EtZ/l6j/ffge5OIuvJcOLchk+LAJ5ccgZPvgtQ/mYwmhKrlyu3tUdE6njOUU
R3wi3z8WkcSGHbdgokJlmJcYG5+bcRNHpL5/B9KjgXAMgD5K8mGfg58eAsiox14=
-----END CERTIFICATE-----
subject=/CN=ctrl.codesandbox.io
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
---
SSL handshake has read 4323 bytes and written 461 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA
    Session-ID: DE04028A09E6A274B7EAE857EF75EB026765F5FC9C3D0B6957298789F099434C
    Session-ID-ctx: 
    Master-Key: FD9539EC0D983C3038CA59D02162E4CF55D929E784F26F83F6047D8F90C2B498B22488F6003E4AAEB0574ACC46B08448
    Key-Arg   : None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - 06 70 49 43 77 ca 3c 69-ed d5 bd 5f a3 ed 10 4d   .pICw.<i..._...M
    0010 - f2 fd b5 95 f0 d7 81 62-a2 ef b3 2f fe fa c6 91   .......b.../....
    0020 - 4f 1c 08 e3 f1 a7 e3 82-c1 07 c5 d0 b3 00 f8 e3   O...............
    0030 - 12 cd 73 b0 d8 c9 ca 47-6e a5 d6 37 93 4f a9 ad   ..s....Gn..7.O..
    0040 - 96 e5 63 02 e9 54 78 f9-c4 50 10 3c b5 49 66 29   ..c..Tx..P.<.If)
    0050 - f4 a0 6a 88 7e 11 ee c2-eb 45 b4 97 be 55 09 94   ..j.~....E...U..
    0060 - 15 69 60 d3 a6 8d 52 38-f9 f2 b0 54 da 64 76 b0   .i`...R8...T.dv.
    0070 - 58 f8 9f 44 64 50 5b b1-89 89 f2 71 1c 98 78 ad   X..DdP[....q..x.
    0080 - 4c e4 21 3a 60 8b 21 b3-4e 6a 9f 55 2b 71 60 09   L.!:`.!.Nj.U+q`.
    0090 - 37 3d 46 e7 8b 96 6b 99-4e 1b 09 ef 98 6e bc e6   7=F...k.N....n..
    00a0 - 8e 70 48 66 c0 32 3c 08-d0 4e bf c1 8d 9e 23 2d   .pHf.2<..N....#-

    Start Time: 1711741652
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
closed

> Okay, and try once more :)

**Comment by CompuIves** [comment]
Oh huh... Now it's working fine? Maybe it _was_ a TLS version problem then. That's what I changed. Well, glad that it's working for you now!

**Comment by waybig125** [comment]
> Oh huh... Now it's working fine? Maybe it _was_ a TLS version problem then. That's what I changed. Well, glad that it's working for you now!

Yeah, I think the same because now the curl command is also verifying the certificate. Thanks for the help!

**Comment by Elwood-P** [comment]
I'm getting the same problem trying to access a devbox. It's pretty bad that there seems to be no way to access my code. I don't care about the environment at this stage I just want my code back please!

![CleanShot 2024-04-10 at 10 46 26](https://github.com/codesandbox/codesandbox-client/assets/8029011/c63bb2ac-b447-4164-9992-17b057db362a)

**Comment by CompuIves** [comment]
Hey @Elwood-P, could you try again? I tried starting it just now, and it succeeded. I think that the VM was out of disk space before, which prevented it to start. We've now deployed a fix to make VM starts more resilient for those cases.

**Comment by Elwood-P** [comment]
Thank you @CompuIves for your quick response and fix. The devbox can be accessed now.

**Comment by serranoarevalo** [comment]
This is still happening.

Even after paying and adding credits to my account.

There isn't a "Restart microVM" button either.

![Screenshot 2024-04-18 at 22 41 28](https://github.com/codesandbox/codesandbox-client/assets/3612017/d554515a-39bd-4cf3-9304-39c39d1c8fef)

**Comment by CompuIves** [comment]
Hey @serranoarevalo, this should be fixed now. Two bugs are fixed:

1. We don't show "Authorize application" anymore when you get this error. Instead, you can restart the VM from there.
2. The VM had a full disk due to one of our processes that was writing too many logs. This is now fixed as well, it won't write as many logs anymore.

So the VM should work as expected again, and if something like this happens again (let's hope not!) the restart button should fix it.

**Comment by thearraspolice** [comment]
My CodeSandbox project is not loading. I believe that it may be due to running out of disk space, but I am not entirely sure. 

I would really like to have my project back, because I cannot edit the code or fork the project. I am also using the Pro Plan.
![image](https://github.com/codesandbox/codesandbox-client/assets/157838180/a0d979f6-3a1e-4d02-8bc4-debb07bf42c7)

**Comment by CompuIves** [comment]
Does it work now? Our hosting provider in US had a moment of downtime today. We're working on a solution where we can reroute existing VMs to EU when that happens.

**Comment by thearraspolice** [comment]
Thank you, it works perfectly. (I deleted my issue on GitHub when it
started working :))

**Comment by aryothezombie** [comment]
help please the sandbox keeps collapsing within 10 to 15 minutes and doesnt work it gives the same error

**Comment by filipelima18** [comment]
> help please the sandbox keeps collapsing within 10 to 15 minutes and doesnt work it gives the same error

Can you share the URL of the Sandbox so we can investigate this?

**Comment by winston86zhu** [comment]
Hi we are seeing the same issue 
<img width="715" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/47490361/eff3a437-9ad8-4132-a79e-c0bc2b817dce">

**Comment by CompuIves** [comment]
> Hi we are seeing the same issue

This should be fixed now! Some VMs that started on April 20th in US had issues with persisting git changes while they were booting. The bug behind this has been fixed.

**Comment by CompuIves** [comment]
Ah, makes sense. The original bug is fixed but the VMs affected are not "repaired". I'm writing a fix for that now, should be live in an hour.

**Comment by CompuIves** [comment]
The fix has just been deployed! Could you verify that it works again?

**Comment by stephaniedavidson** [comment]
Also having this issue multiple times on different repos, tried forking. https://codesandbox.io/p/devbox/threlte-obj-with-glsl-tex-forked-n9tlfr

**Comment by jdorantes** [comment]
Hi there, I'm also seeing the issue on a couple of repo based sandboxes. Here is the screenshot and link:

<img width="825" alt="Screenshot 2024-05-03 at 12 16 45 PM" src="https://github.com/codesandbox/codesandbox-client/assets/5481903/27dc88d3-1e19-41e3-aed7-70e280aa331a">

https://codesandbox.io/p/github/jdorantes/battleboat/gh-pages?workspaceId=521ca564-b9fc-4f16-8445-9d170083dbb7

and this one:

<img width="751" alt="Screenshot 2024-05-03 at 12 21 24 PM" src="https://github.com/codesandbox/codesandbox-client/assets/5481903/1994a975-5a93-4ff5-8dbc-72b766b4b471">
https://codesandbox.io/p/github/jdorantes/battleboat/draft/cool-dewdney?workspaceId=521ca564-b9fc-4f16-8445-9d170083dbb7

Thanks for your help!

**Comment by CompuIves** [comment]
Our US cluster had blocked on of our nodes, and we've been working on rerouting the traffic. Now everything should be back to normal again. Could you check again if the VMs start?

**Comment by MylesA94** [comment]
Also having this issue with a forked repo.
![image](https://github.com/codesandbox/codesandbox-client/assets/32497812/1e83d165-0bc8-46a9-a504-2ea270ab1d64)

**Comment by filipelima18** [comment]
Hi @MylesA94! Are you still experiencing this error? We released another fix yesterday that might have solved this for you. If not, can you share the privacy of the Devbox to "unlisted" so we can test it on our end?

**Comment by MylesA94** [comment]
Hello @filipelima18, thank you for the follow up I will re check today to verify if the issue has been solved by the most recent fix and get back to you with an update.

**Comment by MylesA94** [comment]
@filipelima18 looks like things were resolved with the recent fix. Thanks for reaching out and thanks for the patients.

**Comment by kimvuVarner** [comment]
I don't know if this belongs here, but this sandbox https://codesandbox.io/p/devbox/swiper-react-lazy-load-images-rllglc?file=%2Fsrc%2FApp.jsx worked perfectly yesterday. But opening it today gives me this error:
![image](https://github.com/user-attachments/assets/26b61926-b873-4465-871a-f6c734a893fb)

**Comment by jdorantes** [comment]
Is there an issue going on? None of my sandboxes are able to start. All of them give me the same error:

Error: 
Version: 0.0.358
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: wsycv8

Thanks for the help!

**Comment by jdorantes** [comment]
> Is there an issue going on? None of my sandboxes are able to start. All of them give me the same error:
> 
> Error: Version: 0.0.358 Environment: production Event: Initial connect to Pitcher State: ERROR Branch: wsycv8
> 
> Thanks for the help!

Can I get some help with the above? Thanks!

**Comment by CarterOgunsola** [comment]
Hey I'm still running into this issue, I've emailed support and tweeted at support and still no response. This is really important for a project that need to launch EOW.

https://codesandbox.io/p/github/CarterOgunsola/vana-x-team/csb-txvvmd/draft/wild-breeze?workspaceId=77ae63ab-8083-48a9-b1c9-cac85586a34b

![image](https://github.com/user-attachments/assets/c030678c-d714-4634-baba-64cf1e68917e)

Error: 
Version: 0.0.359
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: txvvmd

**Comment by CompuIves** [comment]
I've responded in support.

> Is there an issue going on? None of my sandboxes are able to start. All of them give me the same error:

Ah I've missed this. Apologies for the late reply. I checked the linked sandbox and from what I can see in the logs everything is working as expected, do you still experience this issue? Generally it helps if you contact support directly, we should respond within a day on there.

**Comment by chatranjan7865** [comment]
How i can setup my own microvm and sandbox ?

**Comment by filipelima18** [comment]
> How i can setup my own microvm and sandbox ?

Hi @chatranjan7865. Do you mean self-hosting your own version of microVMs and Sandboxes? If so, we currently do not support it.

**Comment by filipelima18** [comment]
Hi @betawaxx - the link is opening normally for me. Can you confirm if the issue is still happening on your end?

**Comment by CompuIves** [comment]
Oh that's very bad, I'm sorry for that experience! I will answer today to help recover.

The reload button after 5 minutes is expected, as we will hibernate a VM after 5 minutes of inactivity (or 30min for pro users). A reload should resume the VM in ~500ms so it should work fast again then. We used to keep a VM running if there was a connection from the editor, but this created some unexpected runtimes for VMs, so I changed our auto-wake behaviour recently to not wake on WebSocket connections.

**Comment by hashnodes09** [comment]
I am still experiencing this issue how to fix this

**Comment by hashnodes09** [comment]
I cant access my vps it saying 

Error: Error: Timed out after 5000ms
Version: 0c12b80
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: ksxmst

**Comment by motorcycles-afk** [comment]
Experiencing this issue today too. Status shows the pitcher is down?? but still all services are up, weird

**Comment by CompuIves** [comment]
@hashnodes09 This is weird, I haven't seen a start for that VM in the last 28 days. Could you send an email to support@codesandbox.io with your account username? Then we can check based on your username in our logs what happened.

@motorcycles-afk Yes, around the time of your message we had an outage on our us-1 cluster due to a DoS attack from a user (from within the cluster, that made it hard to figure out what was causing the load).

@betawaxx I see that the VM has had consistent resume times lately, are you still experiencing the issue? The WebSocket connection error is a good hint, it would indicate that the VM started, but that the agent running inside the VM was unresponsive. Do you have a timestamp of when it was this slow for you?

**Comment by CompuIves** [comment]
Hm, I can connect to your shared sandbox and open the editor with preview. Could it be that you're connected to a corporate network or Turkish ISP? Sometimes they block access to CodeSandbox domains.

Two good tests for this are from the terminal:

```
$ ping ctrl.fc-eu-0.codesandbox.io
PING fc-eu-0.pitcher.csb.app (167.235.8.253): 56 data bytes
64 bytes from xxx: icmp_seq=0 ttl=53 time=32.540 ms
64 bytes from xxx: icmp_seq=1 ttl=53 time=35.633 ms

$ curl https://ctrl.fc-eu-0.codesandbox.io/k6cm7j
Not Found%
```

**Comment by CompuIves** [comment]
Ah, this could mean two things, I think:

1. We only support TLS v1.2 and up, for security reasons. Could you try to force TLS v1.2 when doing curl by adding `--tlsv1.2` to the curl command? That would help identify if it's a TLS issue.
2. This is less likely, but a firewall or proxy could interfere with the connection causing the TLS issue. Could you share the output itself of `curl`, so we can check if the body is what our server responds?

**Comment by av1v3k** [comment]
Thinking when it would resolve.
<img width="584" alt="Image" src="https://github.com/user-attachments/assets/1762788a-f2bb-4ffb-b586-a2810b1c6145" />

**Comment by Arrugonoto** [comment]
I'm not sure what triggered that, maybe a false positive but my antivirus software found this:

![Image](https://github.com/user-attachments/assets/7f8fca4c-6262-4a6c-9cdd-b25ec3fee96e)

Text: We have prevented connection to the page:
'fc-eu-0.pitcher.csb.app' because it is dangerous.
Threat category: URL:Mal

This happened while I have tried to check examples of TanStack form on CodeSandbox

URL: https://codesandbox.io/s/github/tanstack/form/tree/main/examples/react/simple

This link is placed in official TanStack form library page https://tanstack.com/form/latest/docs/overview

**Comment by aaaass5566** [comment]
What is it?

در تاریخ یکشنبه ۲۰ آوریل ۲۰۲۵، ۲۲:۱۲ Krzysztof ***@***.***>
نوشت:
